# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-01 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercate',
            name='cnum',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='usercate',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
