# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-01 07:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20180201_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatfriend',
            name='friend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.User', verbose_name='当前聊天客场用户'),
        ),
        migrations.AlterField(
            model_name='chatfriend',
            name='history',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app01.ChatHistory', verbose_name='聊天内容'),
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='content',
            field=models.CharField(max_length=256, verbose_name='聊天内容'),
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.User', verbose_name='当前聊天主场用户'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=32, verbose_name='分组名'),
        ),
        migrations.AlterField(
            model_name='group',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.User', verbose_name='属于哪个用户'),
        ),
        migrations.AlterField(
            model_name='groupfriend',
            name='friend',
            field=models.ManyToManyField(to='app01.User', verbose_name='分组下的好友'),
        ),
        migrations.AlterField(
            model_name='groupfriend',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app01.Group', verbose_name='分组'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pwd',
            field=models.CharField(max_length=32, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user',
            field=models.CharField(max_length=32, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='usercate',
            name='addr',
            field=models.CharField(max_length=32, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='usercate',
            name='cnum',
            field=models.IntegerField(verbose_name='ID号'),
        ),
        migrations.AlterField(
            model_name='usercate',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='usercate',
            name='phone',
            field=models.IntegerField(verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='usercate',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app01.User', verbose_name='用户'),
        ),
    ]
