# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-01 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_auto_20180201_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isonline',
            field=models.IntegerField(default=0, verbose_name='是否在线'),
        ),
    ]
