# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-02 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_user_isonline'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.FileField(default='avatar/default.jpg', upload_to='avatar/'),
        ),
    ]
